- name: Create S3 bucket
  amazon.aws.s3_bucket:
    name: "{{ s3_bucket_name }}"
    state: present
    region: "{{ aws_region }}"

- name: Launch EC2 instance
  amazon.aws.ec2_instance:
    name: "Ansible-EC2"
    key_name: "{{ ec2_key_name }}"
    instance_type: "{{ ec2_instance_type }}"
    image_id: "{{ ec2_ami }}"
    region: "{{ aws_region }}"
    wait: yes
    count: 1

# Make sure a folder exists in your project directory
- name: Ensure lambda folder exists in project directory
  ansible.builtin.file:
    path: "{{ playbook_dir }}/lambda"
    state: directory
    mode: '0755'
  delegate_to: localhost

# Copy the Lambda ZIP into that folder
- name: Copy Lambda ZIP to project folder
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/aws_services/files/minimal_lambda.zip"
    dest: "{{ playbook_dir }}/lambda/minimal_lambda.zip"
    mode: '0644'
  delegate_to: localhost

# (Optional) list files to confirm
- name: List files in lambda folder
  ansible.builtin.find:
    paths: "{{ playbook_dir }}/lambda"
    file_type: any
  register: dir_contents
  delegate_to: localhost

- debug:
    var: dir_contents.files | map(attribute='path') | list
  delegate_to: localhost

# Use the file from project folder for Lambda creation
- name: Create minimal Lambda functions
  amazon.aws.lambda:
    state: present
    name: "{{ item.name }}"
    runtime: python3.9
    role: "{{ lambda_role_arn }}"
    handler: index.handler
    src: "{{ playbook_dir }}/lambda/minimal_lambda.zip"
    region: "{{ aws_region }}"
  loop: "{{ lambda_functions }}"
  delegate_to: localhost
