- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: true

- name: Copy index.html to web root
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'
  become: true

- name: Ensure NGINX is running
  service:
    name: nginx
    state: started
    enabled: true
  become: true
