---
# tasks file for ec2

- name: Launch EC2 instance
  amazon.aws.ec2_instance:
    name: "{{ aws_tag_name }}"
    key_name: "{{ aws_key_name }}"
    instance_type: "{{ aws_instance_type }}"
    image_id: "{{ aws_image_id }}"
    region: "{{ aws_region }}"
    security_group: "{{ aws_security_group }}"
    wait: yes
    count: 1
    tags:
      Name: "{{ aws_tag_name }}"
  register: ec2

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip_address }}"
    groupname: launched
  loop: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_ip_address }}"
    port: 22
    delay: 10
    timeout: 300
    state: started
  loop: "{{ ec2.instances }}"

- name: Install NGINX on launched instance
  become: yes
  delegate_to: "{{ item.public_ip_address }}"
  loop: "{{ ec2.instances }}"
  loop_control:
    label: "{{ item.public_ip_address }}"
  vars:
    ansible_user: ubuntu
  block:
    - name: Install NGINX
      ansible.builtin.package:
        name: "{{ nginx_package }}"
        state: present

    - name: Start and enable NGINX
      ansible.builtin.service:
        name: "{{ nginx_package }}"
        state: started
        enabled: yes
